### ISSUE TITLE
Exception #major

### ISSUE THREAD

**Issue by 0x00-0x00** [0x00-0x00/crypt#16]
Traceback (most recent call last):
  File "bin/crypt", line 326, in <module>
    main()
  File "bin/crypt", line 315, in main
    Crypter(args)
  File "bin/crypt", line 105, in __init__
    self.key = Encryption.get_key(self.key_bits)
  File "C:\Users\ANDRE\AppData\Local\Programs\Python\Python36\lib\site-packages\shemutils\encryption.py", line 82, in get_key
    return Encryption.hash256(k)
  File "C:\Users\ANDRE\AppData\Local\Programs\Python\Python36\lib\site-packages\shemutils\encryption.py", line 60, in hash256
    return hashlib.sha256(string).digest()
TypeError: Unicode-objects must be encoded before hashing

**Comment by 0x00-0x00** [comment]
** Shemutils Error ** 
I am going to fix it on the correspondent project.
